services:
  - type: web
    name: noemi-portfolio
    env: python
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
